version: '2'

services:

  frontend:
    container_name: frontend
    build: web/project-tracker
    depends_on:
      - backend
    ports:
      - 4200:4200
    command: 'npm run -- ng serve --host 0.0.0.0 --disable-host-check'

  backend:
    container_name: backend
    build: core
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=jdbc:postgresql://db:5432/project_tracker

  db:
    container_name: db
    image: postgres
    volumes:
      - ./core/src/main/resources/database.sql:/docker-entrypoint-initdb.d/1-database.sql
      #      - ./core/src/main/resources/dump/project_tracker.sql:/docker-entrypoint-initdb.d/2-dump.sql
      #      - ./core/src/main/resources/dump/fix_sequences.sql:/docker-entrypoint-initdb.d/3-sequences.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project_tracker
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  db_data: { }
  angular_data: { }
